In [1]:
import numpy as np
from collections import Counter, namedtuple

In [52]:
zeros = np.zeros((9,9),dtype="int16")
easy = np.load("data/easy.npy")
easyChanged = np.load("data/easyChanged.npy")
extrime = np.load("data/extrime.npy")
print(extrime)

[[0 0 9 4 0 0 0 0 6]
 [0 1 0 0 5 0 0 4 0]
 [7 0 0 0 0 6 5 0 0]
 [5 0 0 0 0 1 2 0 0]
 [0 2 0 0 7 0 0 3 0]
 [0 0 4 5 0 0 0 0 9]
 [0 0 8 6 0 0 0 0 1]
 [0 7 0 0 9 0 0 2 0]
 [1 0 0 0 0 8 9 0 0]]


In [68]:
def getBorad(matrix):
    borad = "#-------+-------+-------#\n"
    for y in range(9):
        borad += divyUp(matrix[y]) + "\n"
        if y % 3 == 2:
            borad += "#-------+-------+-------#\n"
    return borad

def divyUp(arr):
    s = "| "
    for i in range(9):
        s += '{} '.format(' 'if arr[i] == 0 else arr[i])
        if i % 3 == 2:
            s += "| "
    return s

def printBorad(matrix):
    print(getBorad(matrix))

In [71]:
printBorad(extrime)

#-------+-------+-------#
|     9 | 4     |     6 | 
|   1   |   5   |   4   | 
| 7     |     6 | 5     | 
#-------+-------+-------#
| 5     |     1 | 2     | 
|   2   |   7   |   3   | 
|     4 | 5     |     9 | 
#-------+-------+-------#
|     8 | 6     |     1 | 
|   7   |   9   |   2   | 
| 1     |     8 | 9     | 
#-------+-------+-------#



In [3]:
def sudokuGetRegions(borad, x, y):
    borad = np.matrix(borad)
    regions = (
        borad[x].A1,                                # ROW
        borad[:,y].A1,                              # COL
        borad[x//3*3:x//3*3+3 ,y//3*3:y//3*3+3].A1  # BOX
    )
    return regions

In [4]:
sudokuGetRegions(extrime, 3,2)

(array([5, 0, 0, 0, 0, 1, 2, 0, 0]),
 array([9, 0, 0, 0, 0, 4, 8, 0, 0]),
 array([5, 0, 0, 0, 2, 0, 0, 0, 4]))

In [46]:
def isPossible(borad, x, y, value = 0):
    newborad = borad.copy()
    newborad[x,y] = value if value > 0 else newborad[x,y]
    regions = sudokuGetRegions(newborad, x, y)
    # clear all zeros and get unique with counts
    valueSets = [Counter(np.delete(reg, np.where(reg == 0))) for reg in regions] 
    for valueSet in valueSets:
        # check the values of valueset for anything that is grater the 1  
        countGTone = len(np.where(np.array(list(valueSet.values())) > 1)[0]) 
        if countGTone > 0: return False
    return True

In [47]:
print(extrime[3,0])
a = isPossible(extrime, 3,0)
print(a)

5
True


In [132]:
def solve(borad):
    for y in range(9):
        for x in range(9):
            if borad[x,y] == 0:
                for val in range(1,10):
                    if isPossible(borad, x, y, val):
                        borad[x,y] = val
                        yield from solve(borad)
                        borad[x,y] = 0
                return borad
    yield borad

In [133]:
activeBoard = extrime.copy()
# printBorad(extrime)
itters = 0
printBorad(activeBoard)

a = solve(activeBoard)
for b in a:
    # print(itters)
    printBorad(activeBoard)
print(itters)

#-------+-------+-------#
|     9 | 4     |     6 | 
|   1   |   5   |   4   | 
| 7     |     6 | 5     | 
#-------+-------+-------#
| 5     |     1 | 2     | 
|   2   |   7   |   3   | 
|     4 | 5     |     9 | 
#-------+-------+-------#
|     8 | 6     |     1 | 
|   7   |   9   |   2   | 
| 1     |     8 | 9     | 
#-------+-------+-------#

#-------+-------+-------#
| 2 5 9 | 4 3 7 | 1 8 6 | 
| 8 1 6 | 2 5 9 | 3 4 7 | 
| 7 4 3 | 8 1 6 | 5 9 2 | 
#-------+-------+-------#
| 5 9 7 | 3 8 1 | 2 6 4 | 
| 6 2 1 | 9 7 4 | 8 3 5 | 
| 3 8 4 | 5 6 2 | 7 1 9 | 
#-------+-------+-------#
| 9 3 8 | 6 2 5 | 4 7 1 | 
| 4 7 5 | 1 9 3 | 6 2 8 | 
| 1 6 2 | 7 4 8 | 9 5 3 | 
#-------+-------+-------#

6212
