# Simple Text Analyzer

ok so here have have some data with some sencetes and tags. We write something and the AI will try to geuss what it's.
 

In [1]:
import json
from io import open
import re
import numpy as np

In [2]:
# load data 
with open("data.json", "r") as d:
    data = json.load(d)
data

{'tags': [{'tag': 'greetings',
   'sentences': ['Hello!',
    'Hey',
    "What's up",
    'Nice to meet you',
    'Good morning.',
    'Good evening',
    'Good morning',
    'Good afternoon',
    'Good evening',
    'It’s nice to meet you',
    'It’s a pleasure to meet you']},
  {'tag': 'identity',
   'sentences': ['Who are you?',
    'What are you?',
    'What is you name?',
    'What do you do?']},
  {'tag': 'jokes',
   'sentences': ['Did you hear about the mathematician who’s afraid of negative numbers?',
    "Why do we tell actors to 'break a leg?'",
    'Helvetica and Times New Roman walk into a bar.',
    'Did you hear about the actor who fell through the floorboards?']}]}

In [11]:
# totalt word list 
wordlist = []
tag_wordlist = dict()
pattern = re.compile('\w+')
for tag in data['tags']:
    tag_wordlist[tag['tag']] = []
    for s in tag['sentences']:
        # print(tag['tag'],[a for a in p.findall(s)])
        wl = [a.lower() for a in pattern.findall(s)]
        tag_wordlist[tag['tag']].extend(wl)
        wordlist.extend(wl)

# wordlist.sort()
wordlist = list(set(wordlist))
wordlist.sort()
print(tag_wordlist,'\n', wordlist)
len(wordlist)


{'greetings': ['hello', 'hey', 'what', 's', 'up', 'nice', 'to', 'meet', 'you', 'good', 'morning', 'good', 'evening', 'good', 'morning', 'good', 'afternoon', 'good', 'evening', 'itâ', 's', 'nice', 'to', 'meet', 'you', 'itâ', 's', 'a', 'pleasure', 'to', 'meet', 'you'], 'identity': ['who', 'are', 'you', 'what', 'are', 'you', 'what', 'is', 'you', 'name', 'what', 'do', 'you', 'do'], 'jokes': ['did', 'you', 'hear', 'about', 'the', 'mathematician', 'whoâ', 's', 'afraid', 'of', 'negative', 'numbers', 'why', 'do', 'we', 'tell', 'actors', 'to', 'break', 'a', 'leg', 'helvetica', 'and', 'times', 'new', 'roman', 'walk', 'into', 'a', 'bar', 'did', 'you', 'hear', 'about', 'the', 'actor', 'who', 'fell', 'through', 'the', 'floorboards']} 
 ['a', 'about', 'actor', 'actors', 'afraid', 'afternoon', 'and', 'are', 'bar', 'break', 'did', 'do', 'evening', 'fell', 'floorboards', 'good', 'hear', 'hello', 'helvetica', 'hey', 'into', 'is', 'itâ', 'leg', 'mathematician', 'meet', 'morning', 'name', 'negative', 'new

49

So now I'm gonna try to make a matrix of bools/counts,

TagName   | hello | new | why | you    
----------|-------|-----|-----|--------
greetings | 1     | 0   | 1   | 1 or 3 
identity  | 0     | 0   | 0   | 1 or 4 
jokes     | 0     | 1   | 1   | 1 or 2 
 

In [12]:
mat = np.zeros((len(wordlist),len(tag_wordlist)), 'int8')
for ix, word in enumerate(wordlist):
    for iy, tag in enumerate(tag_wordlist):
        for w in tag_wordlist[tag]:
            if w == word:
                mat[ix,iy] += 1
for i, word in enumerate(wordlist):
    print(mat[i], word)

[1 0 2] a
[0 0 2] about
[0 0 1] actor
[0 0 1] actors
[0 0 1] afraid
[1 0 0] afternoon
[0 0 1] and
[0 2 0] are
[0 0 1] bar
[0 0 1] break
[0 0 2] did
[0 2 1] do
[2 0 0] evening
[0 0 1] fell
[0 0 1] floorboards
[5 0 0] good
[0 0 2] hear
[1 0 0] hello
[0 0 1] helvetica
[1 0 0] hey
[0 0 1] into
[0 1 0] is
[2 0 0] itâ
[0 0 1] leg
[0 0 1] mathematician
[3 0 0] meet
[2 0 0] morning
[0 1 0] name
[0 0 1] negative
[0 0 1] new
[2 0 0] nice
[0 0 1] numbers
[0 0 1] of
[1 0 0] pleasure
[0 0 1] roman
[3 0 1] s
[0 0 1] tell
[0 0 3] the
[0 0 1] through
[0 0 1] times
[3 0 1] to
[1 0 0] up
[0 0 1] walk
[0 0 1] we
[1 3 0] what
[0 1 1] who
[0 0 1] whoâ
[0 0 1] why
[3 4 2] you


OK Now we can start modeling...